baseURL = "http://www.metaville.info/"
languageCode = "fr-ca"
title = "Metaville"

theme = "reveal-hugo"

[outputFormats.Reveal] 
baseName = "index" 
mediaType = "text/html" 
isHTML = true 

[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.45.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.45.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.45.1"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.45.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
